In [1]:
# (1) 첨부된 code에서 Q-Learning이 어떻게 적용되었는지 정리해보세요!
# (2) 코드에서 gamma 값을 0.5 또는 0.99로 바꾸어 실행해보고, gamma 값을 다르게 설정하면 Q-matrix가 어떻게 변하는지 비교하여 정리해보세요!



# (1) 첨부된 code에서 Q-Learning이 어떻게 적용되었는지 정리해보세요!
# (2) 코드에서 gamma 값을 0.5 또는 0.99로 바꾸어 실행해보고, gamma 값을 다르게 설정하면 Q-matrix가 어떻게 변하는지 비교하여 정리해보세요!

gamma = 0.5 
final q-matrix : 
[[ 0. -5.  0. -1. -1.]
 [ 0. 10.  0.  0.  0.]
 [-1.  0.  0. 10.  4.]
 [ 0.  0.  0.  0.  0.]]


gamma = 0.99
final q-matrix : 
[[ 0.    -0.1    0.     8.9    7.811]
 [ 0.    10.     7.811  0.    -1.   ]
 [ 7.811  0.     0.    10.     8.9  ]
 [ 0.     0.     0.     0.     0.   ]]

 낮은gamma는, 미래의 보상보다 현재의 보상을 중시하여 짧은 경로를 선호하는 식으로 Q-matrix가 변화하였다. 이에 반해 gamma=0.99로 설정할 시, 미래 보상을 더욱 중요하게 고려하여 최적의 보상을 얻기 위한 Q-matrix가 학습됨.

In [2]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.8

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state 
# 1 is state to the right of 0
# 2 is the snake-pit state 
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]]) # Reward 행렬. 각 state에서 특정 행동을 할 때 받을 수 있는 보상 정리

q_matrix = np.zeros((4,5)) # Q-table 초기화

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0], # 특정 행동 한 뒤, 이동할 수 있는 다음 상태
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions 
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state]) # 랜덤한 행동 하나 선택
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards) # 벨만 방정식 활용하여 Q 업데이트 (gamma는 할인률 계수)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3: # 목표 상태 도달
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


[[ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0. -1.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
goal state reached
[[ 0.  0.  0.  7.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0.  7.  0.]
 [ 0. 10.  0.  0.  7.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.   0.   0.   7.   0. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
[[  0.  -10.    0.    7.    0. ]
 [  0.   10.    4.6   0.    7. ]
 [  0.    0.    0.    0.    0. ]
 [  0.    0.    0.    0.    0. ]]
Q-matrix is updated
[[  0.  -10.    0.    7.    0. ]
 [  0.   10.    4.6   0.    7. ]
 [  0.    0.    0.    0.   -1. ]
 [  0.    0.    0.    0.    0. ]]
Q-matrix is updated
[[  0.  -10.    0.    7.    0. ]
 [  0.   10.    4.6   0.    7. ]
 [  0.    0.    0.   10.

In [3]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.5

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state 
# 1 is state to the right of 0
# 2 is the snake-pit state 
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]]) # Reward 행렬. 각 state에서 특정 행동을 할 때 받을 수 있는 보상 정리

q_matrix = np.zeros((4,5)) # Q-table 초기화

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0], # 특정 행동 한 뒤, 이동할 수 있는 다음 상태
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions 
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state]) # 랜덤한 행동 하나 선택
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards) # 벨만 방정식 활용하여 Q 업데이트 (gamma는 할인률 계수)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3: # 목표 상태 도달
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


[[ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[  0. -10.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.  10.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
goal state reached
[[ 0. -5.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -5.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [-1.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -5.  0.  0. -1.]
 [ 0.  0.  0. 

In [4]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.99

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state 
# 1 is state to the right of 0
# 2 is the snake-pit state 
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]]) # Reward 행렬. 각 state에서 특정 행동을 할 때 받을 수 있는 보상 정리

q_matrix = np.zeros((4,5)) # Q-table 초기화

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0], # 특정 행동 한 뒤, 이동할 수 있는 다음 상태
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions 
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state]) # 랜덤한 행동 하나 선택
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards) # 벨만 방정식 활용하여 Q 업데이트 (gamma는 할인률 계수)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3: # 목표 상태 도달
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.   0.]
 [  0.   0.   0.   0.   0.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.   0.]
 [  0.   0.  -1.   0.   0.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.   0.]
 [  0.   0.  -1.   0.   0.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.   0.]
 [  0.   0.  -1.   0.   0.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.   0.]
 [  0.   0.  -1.   0.   0.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.   0.]
 [  0.   0.  -1.   0.   0.]
 [ -1.   0.  