In [ ]:
# (1) 첨부된 code에서 Q-Learning이 어떻게 적용되었는지 정리해보세요!
# (2) 코드에서 gamma 값을 0.5 또는 0.99로 바꾸어 실행해보고, gamma 값을 다르게 설정하면 Q-matrix가 어떻게 변하는지 비교하여 정리해보세요!

In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.99

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state 
# 1 is state to the right of 0
# 2 is the snake-pit state 
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions 
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.  10.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
goal state reached
[[ 0.  -0.1  0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  10.   0. ]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
[[ 0.  -0.1  0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  10.   8.9]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
[[ 0.  -0.1  0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [-1.   0.   0.  10.   8.9]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
[[ 0.  -0.1  0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [-1.   0.   0.  10.   8.9]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
[[ 0.  -0.1  0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [-1.   0.   0.  10.   8.9]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
goal state reached
[[ 0.  -0.1  0.   0.   0. ]
 [ 

정리: 4개의 상태와 5개의 행동(상,하,좌,우,무행동)을 가진 간단한 그리드 월드에서 Q-Learning을 구현했습니다. Q-테이블은 0으로 초기화되며, 10번의 에피소드 동안 에이전트가 시작 상태(0)에서 목표 상태(3)까지 무작위 행동을 선택하며 학습합니다. 각 단계에서 Q(s,a) = R(s,a) + γ max(Q(s',a')) 공식으로 Q-값을 갱신하며, 감마값 0.8을 사용해 미래 보상의 중요도를 조절합니다. 환경 모델 없이도 학습 가능한 모델 프리 방식이 특징입니다.

감마값 비교: 감마값이 클수록 미래 보상을 더 중요하게 고려하여 장기적인 관점의 전략을 학습하고, 작을수록 즉각적인 보상을 중시하는 단기적인 전략을 학습합니다.