In [ ]:
# (1) 첨부된 code에서 Q-Learning이 어떻게 적용되었는지 정리해보세요!
# (2) 코드에서 gamma 값을 0.5 또는 0.99로 바꾸어 실행해보고, gamma 값을 다르게 설정하면 Q-matrix가 어떻게 변하는지 비교하여 정리해보세요!

In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt

gammas = [0.5, 0.8, 0.99]

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state 
# 1 is state to the right of 0
# 2 is the snake-pit state 
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions 
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for gamma in gammas:  # 각 gamma 값에 대해 실행
    q_matrix = np.zeros((4, 5))  # 매번 새로운 Q-행렬 초기화
    print(f"\n===== Gamma: {gamma} =====")

    for _ in range(10):  # 10 episodes
        start_state = 0
        current_state = start_state
        while current_state != 3:
            action = random.choice(valid_action[current_state])
            next_state = transition_matrix[current_state][action]
            
            future_rewards = []
            for action_nxt in valid_action[next_state]:
                future_rewards.append(q_matrix[next_state][action_nxt])
                
            q_state = reward[current_state][action] + gamma * max(future_rewards)
            q_matrix[current_state][action] = q_state
            current_state = next_state
            
    print("Final Q-Matrix:")
    print(q_matrix)



===== Gamma: 0.5 =====
Final Q-Matrix:
[[ 0. -5.  0.  4.  1.]
 [ 0. 10.  1.  0.  4.]
 [ 1.  0.  0. 10.  4.]
 [ 0.  0.  0.  0.  0.]]

===== Gamma: 0.8 =====
Final Q-Matrix:
[[ 0.  -2.   0.   7.   4.6]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.   7. ]
 [ 0.   0.   0.   0.   0. ]]

===== Gamma: 0.99 =====
Final Q-Matrix:
[[ 0.    -0.1    0.     8.9    7.811]
 [ 0.    10.     7.811  0.     8.9  ]
 [ 7.811  0.     0.    10.     8.9  ]
 [ 0.     0.     0.     0.     0.   ]]


## 각 gamma 값에 대한 해석
### **Gamma=0.5**
- q_matrix에서 현재 보상에 비해 미래 보상이 상대적으로 적게 반영됨.
- 미래 보상이 덜 중요하므로 q_matrix의 값들이 현재 보상에 가까운 값을 유지하는 경향을 보임.
### **Gamma=0.8**
- 미래 보상의 영향이 커지기 시작해 감마가 0.5일 때보다 더 큰 값들이 등장하고, 이전 상태의 보상이 더 잘 반영됨.
### **Gamma=0.99**
- 미래 보상의 중요도가 매우 커지며 장기적인 보상에 더 큰 가중치를 두고 학습함.
- q_matrix 값이 더 높아지는 경향이 있고, 미래 보상을 더 많이 반영하여 최적의 경로를 찾으려고 함.

## 요약
- gamma 값이 클수록 Q-값에 미래 보상의 영향이 커지고, gamma 값이 작을수록 현재 보상에 더 많이 의존함.
- gamma가 클수록 더 큰 값을 가진 q_matrix가 형성되며, 이는 미래 보상을 반영하려는 강화학습 에이전트의 경향을 나타냄.