In [ ]:
# (1) 첨부된 code에서 Q-Learning이 어떻게 적용되었는지 정리해보세요!
# (2) 코드에서 gamma 값을 0.5 또는 0.99로 바꾸어 실행해보고, gamma 값을 다르게 설정하면 Q-matrix가 어떻게 변하는지 비교하여 정리해보세요!

In [3]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.5

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state
# 1 is state to the right of 0
# 2 is the snake-pit state
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


[[ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0. -1.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0. -1. -1.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0. -1. -1.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0. -1. -1.]
 [ 0.  0. -1.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0. -1. -1.]
 [ 0. 10. -1.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
goal state reached
[[ 0.  0.  0.  4. -1.]
 [ 0. 10. -1.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0.  4. -1.]
 [ 0. 10.  1.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0.  4. -1.]
 [ 0. 10.  1.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0

In [4]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.99

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state
# 1 is state to the right of 0
# 2 is the snake-pit state
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


[[ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0. -1. -1.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
goal state reached
[[  0. -10.   0.  -1.  -1.]
 [  0.  10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.  -1.]
 [  0.  10.   0.   0.   0.]
 [  0.   0.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.  -1.]
 [  0.  10.   0.   0.   0.]
 [  0.   0.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.  -1.]
 [  0.  10.   0.   0.   0.]
 [  0.   0.   0.  10.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
goal state reached
[[  0.   -10.     0.    -1.    -1.99]
 [  0.    10.     0.     0.     0.  ]
 [  0.     0.  

1) 코드에서 Q-Learning이 적용된 방식 정리


	1.	상태와 행동 정의
	•	상태(state):
	•	총 4개의 상태가 존재하며, 번호로 0, 1, 2, 3으로 표현됩니다.
	•	상태 0: 시작 상태
	•	상태 1: 상태 0의 오른쪽에 위치
	•	상태 2: 보통 벌점이 큰 상태
	•	상태 3: 목표 상태
	•	행동(action):
	•	코드에서는 5개의 행동이 있으며, 인덱스로는 [0: Up, 1: Down, 2: Left, 3: Right, 4: No Action]로 사용됩니다.
	•	각 상태마다 가능한 유효 행동(valid_action)이 미리 정의되어 있으며, 이를 통해 무효한 행동은 선택되지 않도록 합니다.
	2.	보상(reward) 및 전이(transition) 정의
	•	reward matrix:
	•	각 상태에서 특정 행동을 취했을 때 받을 보상이 미리 정의되어 있습니다. (예: 상태 1에서 Down 행동을 선택하면 +10의 보상을 받음)
	•	transition matrix:
	•	현재 상태와 행동에 따라 다음 상태가 결정됩니다. (예: 상태 0에서 오른쪽(Right, 인덱스 3) 행동을 선택하면 상태 1로 전이)
	3.	Q-Matrix 초기화 및 업데이트
	•	초기화:
	•	모든 Q값을 0으로 초기화한  q_matrix  (상태 times 행동 행렬)을 사용합니다.
	•	업데이트 과정:
	•	여러 에피소드(여기서는 10회)에 대해 반복하면서 시작 상태(0)에서 목표 상태(3)에 도달할 때까지 진행합니다.
	•	각 단계에서:
	1.	현재 상태에서 가능한 유효 행동 중 하나를 무작위로 선택합니다.
	2.	선택한 행동에 따라 전이 행렬을 통해 다음 상태를 결정합니다.
	3.	다음 상태에서 가능한 모든 유효 행동의 현재 Q값들 중 최댓값을 찾습니다.
	4.	Q-Learning 업데이트 공식에 따라 현재 상태와 선택한 행동에 대해 Q값을 업데이트합니다.
	•	업데이트 식:
	5.	업데이트된 Q값은  q_matrix 에 저장되고, 현재 상태를 s로 갱신합니다.
	6.	목표 상태(3)에 도달하면 해당 에피소드는 종료됩니다.

이와 같이, 코드에서는 에피소드마다 탐색을 진행하며 각 상태에서의 행동 선택과 Q값 업데이트를 반복하여, 최종적으로 각 state-action 쌍에 대한 Q값을 학습합니다.

2) gamma 값을 0.5 또는 0.99로 바꾸어 실행했을 때 Q-matrix의 변화 비교

gamma의 역할
	gamma  (감쇠 인자)는 미래의 보상에 대한 중요도를 조절합니다.


	1.	gamma = 0.5로 실행:
	•	코드를 실행한 후 최종 Q-matrix의 각 상태-행동 쌍의 값들을 확인합니다.
	•	바로 얻을 수 있는 보상에 의한 값은 업데이트되지만, 이후 단계에서 얻을 수 있는 미래 보상의 영향은 줄어듭니다.
	•	결과적으로, 목표 상태까지의 경로에 대해 Q값이 낮게 산출되거나, 단기 보상이 강조되는 경향이 나타납니다.
	2.	gamma = 0.99로 실행:
	•	동일한 코드에서 감쇠 인자만 0.99로 변경하여 실행합니다.
	•	목표 상태와 같이 멀리 떨어진 높은 보상도 거의 할인 없이 반영되어 Q값이 더 크게 업데이트됩니다.
	•	결과적으로, Q-matrix의 값들이 전반적으로 더 높으며, 장기적인 보상을 고려한 경로 선택이 이루어질 가능성이 있습니다.