In [ ]:
# (1) 첨부된 code에서 Q-Learning이 어떻게 적용되었는지 정리해보세요!
# (2) 코드에서 gamma 값을 0.5 또는 0.99로 바꾸어 실행해보고, gamma 값을 다르게 설정하면 Q-matrix가 어떻게 변하는지 비교하여 정리해보세요!

### **아래 코드의 Q-Learning 적용과정**

상태 (행 기준):

*   0: 시작 상태
*   1: 상태 0의 오른쪽 (중간 상태)
*   2: 뱀 구덩이(위험 상태)
*   3: 목표 상태(보물 상태)

행동 (열 기준, 행동에 대한 매핑):

*   0: 위로 이동 (U)
*   1: 아래로 이동 (D)
*   2: 왼쪽으로 이동 (L)
*   3: 오른쪽으로 이동 (R)
*   4: 아무것도 하지 않음 (N)

***Initialization phase***

1.   q_matrix는 4개의 상태와 5개의 가능한 행동(U, D, L, R, N)에 대한 Q값이 모두 0으로 초기화됨
2.   reward 행렬은 상태와 행동에 따라 주어지는 보상을 정의.
3.   gamma는 미래 보상의 할인 요인(discount factor)으로 설정됨

***Episode Implementation***

1.   총 10개의 에피소드가 수행됨
2.   각 에피소드의 시작 상태는 항상 0으로 초기화됨

***Behavior choice***


1.   현재 상태에서 가능한 행동이 무작위적으로 선택됨 with seed

***State Transfer***


1.   선택한 행동에 따라 transition_matrix를 통해 다음 상태로 전이됨.

***Q-value Update***


1.   다음 상태에서 가능한 모든 행동에 대한 미래 보상을 탐ㅎ색
2.   다음 상태에서 가장 큰 Q값을 선택하여 현재 상태의 Q값을 업데이트함
3.   q_matrix에 새로운 Q값을 저장하고, 이 과정이 반복됨




In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.8

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state
# 1 is state to the right of 0
# 2 is the snake-pit state
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)

[[ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[  0. -10.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.  10.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
goal state reached
[[ 0. -2.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -2.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  7.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -2.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [-1.  0.  0. 10.  7.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -2.  0. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [-1.  0.  0. 10.  7.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -2.  0. -1. -1.]
 [ 0.  0.  0.  0. -1.]
 [-1.  0.  0. 10.  7.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -2.  0. -1. -1.]
 [ 0.  0.  0. 

### **Gamma값의 변화에 따른 q-matrix비교( gamma=0.5, 0.99)**

***Gamma(0.99 vs 0.5)***

*   Q(0,3): 상태 0에서 오른쪽으로 이동하는 행동은 어느 정도 보상이 있지만,  Gamma = 0.5에서는 미래 보상의 중요도가 낮아 Q값이 상대적으로 낮고(4), Gamma=0.99에서는 8.9로 상대적으로 높음

*   Q(1, 1): 아래로 이동하면 목표 상태로 바로 도달하므로 Gamma=0.5에서는 최댓값인 10을 가지고, Gamma=0.99도 마찬가지로 책정됨


*   Q(1, 4): 아무것도 하지 않는 경우도 Gamma=0.5에서는 미래 보상을 적게 반영하여 상대적으로 낮은 값인 4를 반영하지만, Gamma=0.99에서는 높은 8.9로 책정
*   Q(0, 1): 아래로 이동하는 행동은 보상이 나쁘기 때문에 gamma=0.99에서는 Q값이 -0.1이지만, 바로 적시의 보상을 원하는 gamma=0.5의 경우는 penalty값이 -5임



> 즉, gamma값이 커질수록 현재보다는 미래에 대한 보상의 관점에서 현재의 어느정도의 손실을 감안하는 방식이라고 볼 수 있음






In [2]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.5

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state
# 1 is state to the right of 0
# 2 is the snake-pit state
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)

[[ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0. -1.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
goal state reached
[[ 0.  0.  0.  4.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0.  4.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
goal state reached
[[  0. -10.   0.   4.   0.]
 [  0.  10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   4.   0.]
 [  0.  10.   0.   0.   0.]
 [  0.   0.   0.  10.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
goal state reached
[[ 0. -5.  0.  4.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -5.  0.  4.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0. 10.  4.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated

In [3]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.99

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state
# 1 is state to the right of 0
# 2 is the snake-pit state
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)

[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.  10.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
goal state reached
[[ 0.  -0.1  0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
[[ 0.  -0.1  0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [-1.   0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
[[ 0.  -0.1  0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [-1.   0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
[[ 0.  -0.1  0.   0.   0. ]
 [ 0.   0.   0.   0.  