In [1]:
# (1) 첨부된 code에서 Q-Learning이 어떻게 적용되었는지 정리해보세요!
# (2) 코드에서 gamma 값을 0.5 또는 0.99로 바꾸어 실행해보고, gamma 값을 다르게 설정하면 Q-matrix가 어떻게 변하는지 비교하여 정리해보세요!

In [14]:
import numpy as np
import random
import matplotlib.pyplot as plt

#gamma = 0.8

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state
# 1 is state to the right of 0
# 2 is the snake-pit state
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for gamma in [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]:  # Outer loop for gamma values
    for i in range(10):  # 10 episodes
        start_state = 0
        current_state = start_state
        while current_state != 3:
            action = random.choice(valid_action[current_state])
            next_state = transition_matrix[current_state][action]
            future_rewards = []
            for action_nxt in valid_action[next_state]:
                future_rewards.append(q_matrix[next_state][action_nxt])
            q_state = reward[current_state][action] + gamma * max(future_rewards)
            q_matrix[current_state][action] = q_state
            #print(f"Gamma: {gamma} | Q-matrix: {q_matrix}")
            current_state = next_state
            if current_state == 3:
                asd = 1
                #print('goal state reached')

    print(f"Gamma: {gamma}")
    print('final q-matrix : ')
    print(q_matrix)

Gamma: 0.1
final q-matrix : 
[[ 0. -9.  0.  0. -1.]
 [ 0. 10. -1.  0.  0.]
 [-1.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.]]
Gamma: 0.2
final q-matrix : 
[[ 0.  -8.   0.   1.  -0.8]
 [ 0.  10.  -0.8  0.   1. ]
 [-0.8  0.   0.  10.   1. ]
 [ 0.   0.   0.   0.   0. ]]
Gamma: 0.3
final q-matrix : 
[[ 0.  -7.   0.   2.  -0.4]
 [ 0.  10.  -0.4  0.   2. ]
 [-0.4  0.   0.  10.   2. ]
 [ 0.   0.   0.   0.   0. ]]
Gamma: 0.4
final q-matrix : 
[[ 0.  -6.   0.   3.   0.2]
 [ 0.  10.   0.2  0.   3. ]
 [ 0.2  0.   0.  10.   3. ]
 [ 0.   0.   0.   0.   0. ]]
Gamma: 0.5
final q-matrix : 
[[ 0.  -5.   0.   4.   1. ]
 [ 0.  10.   1.   0.   4. ]
 [ 0.5  0.   0.  10.   4. ]
 [ 0.   0.   0.   0.   0. ]]
Gamma: 0.6
final q-matrix : 
[[ 0. -4.  0.  5.  2.]
 [ 0. 10.  2.  0.  5.]
 [ 2.  0.  0. 10.  5.]
 [ 0.  0.  0.  0.  0.]]
Gamma: 0.7
final q-matrix : 
[[ 0.  -3.   0.   6.   3.2]
 [ 0.  10.   3.2  0.   6. ]
 [ 3.2  0.   0.  10.   6. ]
 [ 0.   0.   0.   0.   0. ]]
Gamma: 0.8
final q-matrix : 
[[ 0.  -2.   0.  

gamma를 0.1과 같이 작은 값으로 하면 Q값이 매우 작다. 대부분 행동에 대해 0에 가까운 값을 한다. 즉 에이전트가 미래의 보상을 거의 고려하지 않고 형재 상태에 보상을 중요히 하는 것 처럼 보인다.
감마자 증가할수록 보상에 대한 값이 조금씩 증가한다. 특히 오른쪽 아래로 가는 방향이 더 높은 값을 가지는 것 처럼 보인다. 즉각적인 보상이 비중이 처음에는 더 크지만 감마가 커질 수록 미래 보상이 점차 더 중요한 역할을 한다.