In [ ]:
# (1) 첨부된 code에서 Q-Learning이 어떻게 적용되었는지 정리해보세요!
# (2) 코드에서 gamma 값을 0.5 또는 0.99로 바꾸어 실행해보고, gamma 값을 다르게 설정하면 Q-matrix가 어떻게 변하는지 비교하여 정리해보세요!

In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.5

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state
# 1 is state to the right of 0
# 2 is the snake-pit state
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


[[ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[  0. -10.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.  10.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
goal state reached
[[ 0. -5.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10. -1.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -5.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  4.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -5.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  4.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -5.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  4.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -5.  0.  0.

In [2]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.99

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state
# 1 is state to the right of 0
# 2 is the snake-pit state
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


[[ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0. -1.  0.]
 [ 0.  0. -1.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0. -1.  0.]
 [ 0.  0. -1.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0. -1.  0.]
 [ 0. 10. -1.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
goal state reached
[[ 0.   0.   0.   8.9  0. ]
 [ 0.  10.  -1.   0.  -1. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
[[ 0.     0.     0.     8.9    0.   ]
 [ 0.    10.     7.811  0.    -1.   ]
 [ 0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.   ]]
Q-matrix is updated
[[  0.    -10.      0.      8.9     0.   ]
 [  0.     10.      7.811   0.     -1.   ]
 [  0.      0.      0.  

1. 첨부된 code에서 Q-Learning이 어떻게 적용되었는지 정리해보세요!

이 코드는 Q-Learning 알고리즘을 적용하여 보상을 최대화하는 최적의 행동을 학습하는 과정이다. 에이전트는 총 4개의 상태(state)와 5개의 행동(action)을 가지며, 목표 상태(보물을 찾는 상태)에 도달하는 것이 최종 목표이다
.
초기에는 Q-테이블(q_matrix)이 0으로 설정되며, 학습이 진행됨에 따라 상태-행동 쌍에 대한 Q값이 업데이트된다. 학습은 10개의 에피소드 동안 반복되며, 각 에피소드마다 시작 상태(0번 상태)에서 출발한다. 현재 상태에서 가능한 행동 중 하나를 랜덤하게 선택하고, 그 행동에 따라 다음 상태로 이동한다. 이때 transition_matrix를 사용하여 상태 전이가 이루어진다.

다음 상태에서 가능한 모든 행동의 Q값을 확인한 후, 가장 높은 Q값을 선택하여 미래 보상을 계산한다. 현재 상태의 Q값은 벨만 방정식을 기반으로 업데이트되며, 즉각적인 보상(reward)과 미래 보상의 최대값(max Q(s', a'))을 할인율(gamma)과 함께 반영하여 갱신된다. 이 과정이 반복되면서 에이전트는 점점 더 보상을 극대화하는 방향으로 학습하게 된다.

최종적으로 목표 상태(3번 상태)에 도달하면 학습이 종료되고, 최적의 Q-테이블이 출력된다. 이를 통해 에이전트는 최적의 행동 정책을 학습하며, 보상을 극대화하는 방향으로 행동을 결정할 수 있도록 훈련된다.

2. 코드에서 gamma 값을 0.5 또는 0.99로 바꾸어 실행해보고, gamma 값을 다르게 설정하면 Q-matrix가 어떻게 변하는지 비교하여 정리해보세요!

** gamma = 0.5 (미래 보상을 덜 중요하게 고려) **
- Q-값이 빠르게 감소하며, 가까운 보상에 더 큰 영향을 받는다.

- 학습된 Q-테이블에서는 즉각적인 보상이 높은 경로를 더 선호하며, 먼 미래의 보상은 덜 반영된다.

- 즉, 보상을 받기까지 여러 단계를 거쳐야 하는 행동보다는 당장 받을 수 있는 보상이 있는 행동을 더 많이 선택하는 경향을 보인다.

** gamma = 0.99 (미래 보상을 더 중요하게 고려) **
- 먼 미래의 보상까지 고려하므로, Q-값이 더 크고, 장기적인 최적 경로를 찾는 방향으로 학습된다.

- 더 많은 에피소드가 필요할 수 있지만, 전체적인 정책이 더 최적화될 가능성이 크다.

- 즉, 장기적으로 높은 보상을 받을 수 있는 경로를 선택하는 경향이 강해진다.

